// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:shoqlist/models/shopping_list.dart';
import 'package:shoqlist/models/shopping_list_item.dart';
import 'package:shoqlist/models/user.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(ImportanceAdapter());
    registerAdapter(ShoppingListAdapter());
    registerAdapter(ShoppingListItemAdapter());
    registerAdapter(UserAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(ImportanceAdapter());
    registerAdapter(ShoppingListAdapter());
    registerAdapter(ShoppingListItemAdapter());
    registerAdapter(UserAdapter());
  }
}
